# fly.toml app configuration file generated for uptime on 2026-08-21T01:07:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uptime'
primary_region = 'sin'

[build]
  image = 'louislam/uptime-kuma:2'

[env]
  UPTIME_KUMA_HOST = '0.0.0.0'
  UPTIME_KUMA_PORT = '3001'
  DATA_DIR = '/app/data'

[mounts]
  source = "uptime_kuma_data"
  destination = "/app/data"
  processes = ["app"]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
